project_name: pidpath

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-build
    main: ./cmd/pidpath
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64]
  - id: darwin-build
    main: ./cmd/pidpath
    env: [CGO_ENABLED=1]
    goos: [darwin]
    goarch: [amd64]
